<?php

declare(strict_types=1);

namespace App\Presenters;

use App\Model\ServiceRegistry;

/**
 * Hub — central dashboard with all self-hosted services.
 * Reads ~/projects/default/service-registry.json (generated by Ansible).
 * Sits behind Authentik proxy auth (like Dashboard/Pentest/Remediation).
 */
final class HubPresenter extends BasePresenter
{
	protected string $activeTab = 'hub';

	public function __construct(
		private ServiceRegistry $registry,
	) {
	}

	public function renderDefault(): void
	{
		$data = $this->registry->read();

		$upCount = 0;
		$downCount = 0;
		$categories = [];
		foreach ($data['services'] as $svc) {
			$key = $svc['category'] ?? 'other';
			$categories[$key] = ($categories[$key] ?? 0) + 1;
		}

		$this->template->generatedAt = $data['generated_at'];
		$this->template->hostname = $data['hostname'];
		$this->template->baseDomain = $data['domain'];
		$this->template->services = $data['services'];
		$this->template->grouped = $this->registry->grouped();
		$this->template->totalCount = count($data['services']);
		$this->template->categories = $categories;
	}
}
